"""ajustar modelo CajaItem con relación a Producto

Revision ID: 54b0c73d8df8
Revises: 21b75a92a0d3
Create Date: 2026-05-30 07:32:49.862982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b0c73d8df8'
down_revision = '21b75a92a0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajaitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('caja_item')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint('uq_producto_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_producto_codigo', type_='unique')
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('caja_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('precio_total', sa.FLOAT(), nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cajaitem')
    # ### end Alembic commands ###
